# https://taskfile.dev

version: '3'

tasks:
  network:
    dir: network
    cmds:
      - go run main.go
  
  deploy:
    cmds:
      - forge create --rpc-url http://127.0.0.1:9650/ext/bc/C/rpc --private-key 56289e99c94b6912bfc12adc093c9b51124f0dc54ac7a766b2bc5ccf558d8027 {{.CLI_ARGS}}

  call:
    cmds:
      - cast call --rpc-url http://127.0.0.1:9650/ext/bc/C/rpc {{.CLI_ARGS}}