name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker://ghcr.io/gakonst/foundry:latest
      - name: Build and test in docker
        run: |
          docker run -v $GITHUB_WORKSPACE:/app foundry "forge test --root /app"
          
